{include file="common/header-1.tpl" nocache}
<div class="main_container">
<div class="dash_acct" style="color: black;"><span onClick="window.location='{$config['url']}/dashboard/my'">Dashboard</span>  &gt;&gt;  <span onClick="window.history.back();">Accounting</span>  &gt;&gt;   Transaction <a id="print_invoice" href="#" style="cursor:pointer"><span style="float:right"><input type="button" class="btn btn-danger" value="Print"></span></a>
</div>
<div class="row amt_invoice1">
<div class="amt_paid">Amount:US ${$invoice.amt - $invoice.refundamt}</div>
<div class="invoice">This invoice has been paid in date of {$invoice.pay_date}</div>
</div>
  <div class="row">
  
  <div class="col-md-6">
  <div class="tgray_box">
    <div class=" cust">Customer Billing Information</div>
    <div class="cacell">{$invoice.first_name} {$invoice.last_name}<br />
               {$invoice.email}
               </div>
    <div class="cacell">{$invoice.address},{$invoice.city},{$invoice.state},{$invoice.country}</div>
    <div class="cacell">{$invoice.phone}</div>
  </div>
  </div>

    <div class="col-md-6">
    <div class="tgray_box">
    <div class=" cust">Transaction Trading Partner</div>
    <div class="cacell">{$invoice.name}
               </div>
    <div class="cacell">{if $invoice.uaddress != NULL}{$invoice.uaddress}{/if}</div>
</div>
</div>
</div>
<div class="row tranc_details">
<h5 class="trans_dtls">Transaction Details</h5>
<div class="col-md-3">
<h6 class="trans">Transaction ID</h6>
<h6 class="value">{$invoice.buynow_id}</h6>
<h6 class="value">Created: {$invoice.create_date}</h6>
</div>
<div class="col-md-3">
<h6 class="trans">Transaction Type</h6>
<h6 class="value">Debit</h6>
<h6 class="value">Invoice status: {if $invoice.paid == 1}Paid{/if}{if $invoice.paid == 0}UnPaid{/if}</h6>
</div>
<div class="col-md-3">
<h6 class="trans">Generated by </h6>
<h6 class="value">Billing and Payments</h6>
<h6 class="value">Created date: {$invoice.create_date}</h6>
</div>
<div class="col-md-3">
<h6 class="trans">To</h6>
<h6 class="value">{$invoice.name}</h6>
<h6 class="value">Paid date:{$invoice.pay_date}</h6>
</div>
</div>
<div class="row order_details">
<div class="order">Order Details</div>
<div class="paid">paid via paypal - {$invoice.title}</div>
<div class="prices">Total: US ${$invoice.amt - $invoice.refundamt}</div>
</div>
</div>
{literal}
<script>
$(function(){
$("#print_invoice").click(function(){
createPopup($('header').html()+$('.main_container').html()+$('footer').html());
})
});
</script>
{/literal}
{include file="common/footer-1.tpl" nocache} 